const cardList = [
  { id: "001", name: "ボルメテウス・ホワイト・ドラゴン", image: "./images/001.jpg" },
  { id: "002", name: "ボルシャック・ドラゴン", image: "./images/002.jpg" },
  { id: "003", name: "アクア・ガード", image: "./images/003.jpg" },
  { id: "004", name: "デーモン・ハンド", image: "./images/004.jpg" },
  { id: "005", name: "超竜バジュラ", image: "./images/005.jpg" },
  { id: "006", name: "我我我ガイアール・ブランド", image: "./images/006.jpg" },
  { id: "007", name: "凶戦士 ブレイズ・クロー", image: "./images/007.jpg" },
  { id: "008", name: "ロウゴク童子", image: "./images/008.jpg" },
  { id: "009", name: "逆悪襲 ブランド", image: "./images/009.jpg" },
  { id: "010", name: "轟轟轟 ブランド", image: "./images/010.jpg" },
  { id: "011", name: "グレイト S-駆", image: "./images/011.jpg" },
  { id: "012", name: "襲撃者 鎧ドライブ", image: "./images/012.jpg" },
  { id: "013", name: "轟車 G-突", image: "./images/013.jpg" },
  { id: "014", name: "U・S・A HOKKEEN", image: "./images/014.jpg" },
  { id: "015", name: "ドリル・スコール", image: "./images/015.jpg" },
  { id: "016", name: "クミタテ・チュリス", image: "./images/016.jpg" },
  { id: "017", name: "龍装車 バルチュリス", image: "./images/017.jpg" },
  { id: "018", name: "CRYMAX ジャオウガ", image: "./images/018.jpg" },
  { id: "019", name: "天災 デドダム", image: "./images/019.jpg" },
  { id: "020", name: "ヨビニオン マルル", image: "./images/020.jpg" },
  { id: "021", name: "流星のガイアッシュ・カイザー", image: "./images/021.jpg" },
  { id: "022", name: "フェアリー・ギフト", image: "./images/022.jpg" },
  { id: "023", name: "フェアリー Reライフ", image: "./images/023.jpg" },
  { id: "024", name: "ティンパニ・シンバリー", image: "./images/024.jpg" },
  { id: "025", name: "地龍神の魔陣", image: "./images/025.jpg" },
  { id: "026", name: "フェアリー・ライフ", image: "./images/026.jpg" },
  { id: "027", name: "飛翔龍 5000VT", image: "./images/027.jpg" },
  { id: "028", name: "悪魔龍 ダークマスターズ", image: "./images/028.jpg" },
  { id: "029", name: "終末縫合王 ザ=キラー・キーナリー", image: "./images/029.jpg" },
    // 必要なカードを追加
];
// グローバル変数として公開
window.cardList = cardList;
